"""Create books model

Revision ID: 1fd0d069c367
Revises: c189300cb8b5
Create Date: 2022-11-17 21:59:22.543858
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1fd0d069c367'
down_revision = 'c189300cb8b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'books',
        sa.Column(
            'isbn', sa.VARCHAR(length=36), autoincrement=False, nullable=False
        ),
        sa.Column(
            'book_name',
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            'author',
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            'co_author',
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            'publishing_company',
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            'area', sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            'shelf', sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            'included_at',
            sa.VARCHAR(length=9),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            'updated_at',
            sa.VARCHAR(length=9),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint('isbn', name='books_pkey'),
    )
    # ### end Alembic commands ###
