"""Create books model

Revision ID: 825acd64a04e
Revises: 1fd0d069c367
Create Date: 2022-11-17 22:02:25.863479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '825acd64a04e'
down_revision = '1fd0d069c367'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('isbn', sa.String(length=36), nullable=False),
    sa.Column('book_name', sa.String(length=100), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('co_author', sa.String(length=255), nullable=True),
    sa.Column('publishing_company', sa.String(length=100), nullable=False),
    sa.Column('area', sa.String(length=50), nullable=False),
    sa.Column('shelf', sa.String(length=50), nullable=False),
    sa.Column('included_at', sa.String(length=9), nullable=True),
    sa.Column('updated_at', sa.String(length=9), nullable=True),
    sa.PrimaryKeyConstraint('isbn')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
